#!/usr/bin/env bash
# Check if the number of parameters is less than 4 and display usage if so

if [ "$#" -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Store the parameters in variables for clarity
path_to_file="$1"
ip="$2"
username="$3"
ssh_key="$4"

# Execute scp with the provided parameters to transfer the file
scp -i "$ssh_key" -o StrictHostKeyChecking=no "$path_to_file" "$username"@"$ip":~/

# Check the exit status of scp
if [ "$?" -eq 0 ]; then
    echo "File transfer successful."
else
    echo "File transfer failed."
fi