#!/usr/bin/env bash
# bash script that configures a Nginx server to redirect '/redirect_me' to 'http://youtube.com/'
# redirection is configured as a "301 Moved Permanently"

apt-get update -y
apt-get install nginx -y 
sudo ufw allow 'Nginx HTTP'
sh -c 'echo "Holberton School" > /var/www/html/index.html'
sed -i 'listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/@
cryptocoder permanent;' /etc/nginx/sites-available/default
service nginx restart
